# ============================================================
# Convert a formatted Active Directory CSV file to JSON
#
# Why use "utf-8-sig" for the CSV?
# Some CSV files generated by PowerShell, Excel, or Windows tools
# contain a UTF-8 Byte Order Mark (BOM) at the beginning of the file.
#
# If Python reads the file as plain "utf-8", the BOM can become part
# of the first header name, producing a key similar to:
# "\ufeffName" or "\u00ef\u00bb\u00bf\"Name\""
#
# "utf-8-sig" automatically removes that BOM while reading.
# ============================================================

import csv
import json
from pathlib import Path

# ── File paths ───────────────────────────────────────────────
# Pathlib works cleanly on Windows, macOS, and Linux.
input_file = Path("data") / "AD-User-Info.csv"
output_file = Path("data") / "AD-User-Info.json"

# ── Read the CSV file ────────────────────────────────────────
# newline="" is recommended when using Python's csv module.
# encoding="utf-8-sig" removes a possible UTF-8 BOM from the
# beginning of the file, preventing corruption of the "Name" header.
with input_file.open(
    mode="r",
    newline="",
    encoding="utf-8-sig"
) as src_csv:

    # DictReader uses the CSV header row as dictionary keys.
    #
    # Example row created:
    # {
    #     "Name": "Phoebe Pamela Buffay",
    #     "UserName": "phoebe.buffay",
    #     "EmailID": "phoebe.buffay@easysystems.in",
    #     "DepartmentRole": "Tester",
    #     "Country": "India"
    # }
    csv_reader = csv.DictReader(src_csv)

    # Convert the DictReader iterator into a list so it can be
    # written as a JSON array.
    rows = list(csv_reader)

# ── Write the data to a formatted JSON file ──────────────────
with output_file.open(
    mode="w",
    encoding="utf-8"
) as dest_json:

    # indent=4 makes the JSON easy for humans to read.
    #
    # ensure_ascii=False writes normal Unicode characters directly
    # instead of escaping them as \uXXXX sequences.
    json.dump(
        rows,
        dest_json,
        indent=4,
        ensure_ascii=False
    )

# ── Optional verification step ───────────────────────────────
# Reopen the JSON file to verify that it was successfully created
# and can be parsed as valid JSON.
with output_file.open(
    mode="r",
    encoding="utf-8"
) as json_file:

    # json.load() converts JSON back to a Python list of dictionaries.
    file_data = json.load(json_file)

# Print the complete formatted JSON output to the terminal.
print(json.dumps(file_data, indent=4, ensure_ascii=False))

# Confirm successful completion.
print(f"\nFormatted JSON file created successfully: {output_file}")