# Generated by Django 5.1.5 on 2025-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShowActorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showName', models.CharField(max_length=50)),
                ('actorShowName', models.CharField(max_length=50)),
                ('actorRealName', models.CharField(max_length=50)),
            ],
        ),
    ]
